Quick Links Menu block on Moderation Dashboard
srijanone/ezcontent_publish pull request #42
Opened 2020-10-29 10:17 UTC by saurabh-2k17

2020-11-25 07:47 UTC, vaibhavjain-in requested changes
@saurabh-2k17  Please see changes to be made.

2020-11-25 07:47 UTC, vaibhavjain-in commented on ezcontent_publish.routing.yml
> +  path: '/usershortcut/{shortcut_set}/add-link'
Suggest a better path.

2020-11-25 07:47 UTC, vaibhavjain-in commented on src/Plugin/Block/EzContentUserShortcutBlock.php
> +        ->loadByProperties(['id' => 'shortcut_set_' . $currentUsername . $currentUserId]);
Can this be
```suggestion
        ->loadByProperties(['id' => 'shortcut_set_' . $currentUsername . '_' . $currentUserId]);
```

2020-11-25 07:47 UTC, vaibhavjain-in commented on src/Plugin/Block/EzContentUserShortcutBlock.php
> +          'label' => 'Default Shortcut Set for ' . $currentUsername,
t() missing

2020-11-25 07:47 UTC, vaibhavjain-in commented on src/Plugin/Block/EzContentUserShortcutBlock.php
> +          'id' => 'shortcut_set_' . $currentUsername . $currentUserId,
generate and save the ID value in $id, before If condition

2020-11-25 07:47 UTC, vaibhavjain-in commented on src/Plugin/Block/EzContentUserShortcutBlock.php
> +      $addShortcutLink = $addShortcutLink->toRenderable();
can we club these 2 lines ?

2020-11-25 07:47 UTC, vaibhavjain-in commented on src/Plugin/Block/EzContentUserShortcutBlock.php
> +      $operationShortcutLink = $operationShortcutLink->toRenderable();
Can we club these 2 lines.

2020-11-25 07:47 UTC, vaibhavjain-in commented on templates/usershortcutblock-template.html.twig
> +<section class="user-shortcuts-block-wrapper">
Please rectify formatting issues.

2020-12-03 11:41 UTC, arshadkhan53 requested changes

2020-12-03 11:41 UTC, arshadkhan53 commented on ezcontent_publish.module
> +    'usershortcutblock_template' => [
we should make template name more readable` user_shortcut_block_template`

2020-12-03 11:41 UTC, arshadkhan53 commented on ezcontent_publish.module
> + * {@inheritdoc}
Please check if inherit doc is applicable here

2020-12-03 11:41 UTC, arshadkhan53 commented on ezcontent_publish.routing.yml
> +  path: '/usershortcut/{shortcut_set}/customize'
we can be more specific for path,  like `/usershortcut/{shortcut_set}/list-links`

2020-12-03 11:41 UTC, arshadkhan53 commented on src/Plugin/Block/EzContentUserShortcutBlock.php
> +      $currentuserShortcutsetId = $this->entityTypeManager
```suggestion
      $entityTypeManager= $this->entityTypeManager
```

2020-12-04 12:01 UTC, arshadkhan53 approved these changes
LGTM

2020-12-04 12:20 UTC, merged