EZ-678: Customize quick links to add my own shortcut links
srijanone/ezcontent_publish pull request #53
Opened 2020-11-25 06:45 UTC by saurabh-2k17

2020-12-03 05:39 UTC, arshadkhan53 approved these changes, later dismissed

2020-12-03 05:39 UTC, arshadkhan53 commented on ezcontent_publish.module
> +function ezcontent_publish_form_shortcut_set_customize_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
we can add this in use statement `\Drupal\Core\Form\FormStateInterface`

2020-12-03 08:59 UTC, arshadkhan53 requested changes

2020-12-03 08:59 UTC, arshadkhan53 commented on ezcontent_publish.module
> + * Implements get_usershortcut_links().
Hey @saurabh-2k17 can we move this function to block itself.

2020-12-03 08:59 UTC, arshadkhan53 commented on ezcontent_publish.module
> +    'usershortcutblock_template' => [
```suggestion
    'user_shortcut_block_template' => [
```

2020-12-03 08:59 UTC, arshadkhan53 commented on ezcontent_publish.module
> +    $shortcutObj['links'][] = $shortcutLink;
```suggestion
    $shortcutObj['links'][] = Link::fromTextAndUrl($shortcutTitle, $shortcutLink)->toRenderable();
```

2020-12-07 05:34 UTC, saurabh-2k17 commented
This file has been covered in https://github.com/srijanone/ezcontent_publish/pull/42 this PR. Hence, closing this one.

2020-12-07 05:34 UTC, closed without merging